# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mohammad/Desktop/ECE532/src/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1.xci
# IP: The module: 'hdmi_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mohammad/Desktop/ECE532/src/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Mohammad/Desktop/ECE532/src/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Mohammad/Desktop/ECE532/src/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1.xci
# IP: The module: 'hdmi_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mohammad/Desktop/ECE532/src/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Mohammad/Desktop/ECE532/src/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
