# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: w:/327_2/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_util_ds_buf_0_1/hdmi_util_ds_buf_0_1.xci
# IP: The module: 'hdmi_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/327_2/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_util_ds_buf_0_1/hdmi_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: w:/327_2/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_util_ds_buf_0_1/hdmi_util_ds_buf_0_1.xci
# IP: The module: 'hdmi_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/327_2/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_util_ds_buf_0_1/hdmi_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
