# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: W:/ECE532/0327_colors/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_axis_broadcaster_0_0/hdmi_axis_broadcaster_0_0.xci
# IP: The module: 'hdmi_axis_broadcaster_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/ECE532/0327_colors/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_axis_broadcaster_0_0/hdmi_axis_broadcaster_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_axis_broadcaster_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: W:/ECE532/0327_colors/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_axis_broadcaster_0_0/hdmi_axis_broadcaster_0_0.xci
# IP: The module: 'hdmi_axis_broadcaster_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/ECE532/0327_colors/NexysVideo-master/Projects/hdmi/proj/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_axis_broadcaster_0_0/hdmi_axis_broadcaster_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_axis_broadcaster_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
